In [42]:
from functools import lru_cache as _lru_cache
import numpy as _np

class ChestersWorld:
    def __init__(self,
            nAgents = int(1e5),
            nPlaces = int(1e4),
            nTimes = 24 * 4,
            nCases = 100,
            rSeed = 1066,
            chance = 0.1,
            ):
        self.nAgents, self.nPlaces, self.nTimes, self.nCases, self.rSeed, self.chance = \
            nAgents, nPlaces, nTimes, nCases, rSeed, chance
    def initialise(self):
        nAgents, nPlaces, nTimes, nCases, rSeed = \
            self.nAgents, self.nPlaces, self.nTimes, self.nCases, self.rSeed
        self.rng = rng = _np.random.default_rng(rSeed)
        self.schedule = _np.random.randint(1, nPlaces, (nAgents, nTimes), dtype = 'uint32')
        self.status = status = _np.zeros(nAgents, dtype = bool)
        status[rng.choice(_np.arange(nAgents), nCases, replace = False)] = True
        self.contactLog = []
        self.day = 0
    def iterate(self):
        schedule, status, contactLog, day, rng, chance = \
            self.schedule, self.status, self.contactLog, self.day, self.rng, self.chance
        for contacter in _np.nonzero(status)[0]:
            colocs = _np.argwhere(schedule == schedule[contacter])
            for contactee, timeSlot in colocs:
                place = schedule[contactee, timeSlot]
                if rng.random() < chance:
                    contactEvent = (day, timeSlot, place, contacter, contactee)
                    contactLog.append(contactEvent)
        day += 1
    def go(self, n, /):
        for i in range(n):
            self.iterate()
    def __hash__(self):
        return hash((self.nAgents, self.nPlaces, self.nTimes))

In [55]:
mymodel = ChestersWorld(
    nAgents = int(1e6),
    nPlaces = int(1e5),
    nTimes = 24 * 6,
    nCases = 1,
    )

In [56]:
# %%timeit
mymodel.initialise()

In [57]:
%%timeit
mymodel.iterate()

1.36 s ± 212 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [67]:
mymodel.schedule.nbytes / 2 ** 20

0.54931640625

In [ ]:
_np.argwhere

In [58]:
myarr = _np.random.randint(1, 50, (30, 10))

In [59]:
myarr

array([[42, 36, 33, 47, 40, 27, 27, 12, 23, 37],
       [ 1, 25, 18, 13,  3, 33, 46, 44, 31, 17],
       [ 2, 35, 34, 38,  3,  2, 43, 20, 40, 21],
       [30, 43, 15, 32, 12, 23, 37, 15, 22, 11],
       [ 6, 20, 15, 18,  3, 48, 24, 37, 18, 49],
       [33, 20, 41, 27, 22, 39, 17, 26, 33, 18],
       [ 8, 14, 44, 25,  3, 45,  4, 33, 40, 27],
       [20,  1,  7, 20, 25, 12, 46, 12, 28,  3],
       [18, 36, 24,  9, 41, 38,  8, 49, 14, 44],
       [ 8, 34, 24, 33, 13, 43, 31, 14, 41, 39],
       [24, 13, 20,  3,  9, 36, 49,  8, 28,  1],
       [44, 34, 31, 35, 48, 44, 44, 35, 27, 17],
       [40, 24, 17,  5, 48, 13, 43, 39, 44, 42],
       [24, 44, 12, 11,  8, 18, 22, 22,  9, 10],
       [ 4, 23, 42,  5, 48, 16, 47, 30, 16, 48],
       [25, 14, 30, 29, 30, 19, 19, 19, 18,  9],
       [35, 14, 20, 45, 39,  6, 17, 40, 29, 17],
       [25, 35, 41, 28, 45, 33, 19, 21, 10, 16],
       [30,  4, 26, 29, 44, 14, 24, 36,  4, 43],
       [29, 47, 22,  9,  3,  9, 46, 33, 20,  4],
       [19, 21, 41, 

In [60]:
bigarr = _np.random.randint(1, int(1e2), (30, 10))
selector = _np.random.randint(1, int(1e2), 10)

In [61]:
bigarr.nbytes / 2 ** 20

0.002288818359375

In [63]:
bigarr

array([[71, 45, 23, 15, 16, 81, 21, 72, 62, 54],
       [39, 99, 16, 62,  6, 87, 34, 60, 70, 54],
       [29, 60,  7, 74,  3, 94, 70, 94, 35, 49],
       [63,  3, 90,  8, 84, 11, 61, 54, 32, 70],
       [91, 44,  8, 37, 67, 93, 45,  6, 25, 10],
       [ 6, 54, 29, 51, 99, 40, 27, 84, 60, 55],
       [62, 40, 34, 62, 78, 60,  4, 48, 83, 72],
       [74, 68, 10, 28, 63, 78, 13, 53, 13, 56],
       [77, 57, 99, 34, 29, 13, 94, 68, 55, 67],
       [49, 58, 61, 48, 49, 43, 48, 83, 82, 74],
       [40, 43, 11, 26,  3, 90, 24, 89, 46,  3],
       [25,  5, 73, 20, 70, 52,  4, 97, 22,  5],
       [91, 29, 62, 27, 13, 14, 74,  8, 25, 35],
       [27, 41,  4, 83,  5, 39, 19, 76, 33, 12],
       [61, 23, 67, 63, 95, 13,  7, 40, 71, 92],
       [78, 48,  2, 45, 35, 88, 43, 12, 47,  7],
       [91, 88, 78, 21, 64, 92, 95, 66,  9,  8],
       [20, 29, 69, 63, 91,  2, 49, 33, 96, 88],
       [60, 53, 16, 18, 44, 12, 23, 64, 79, 76],
       [94, 28, 86, 60, 56, 55, 99, 97, 24, 24],
       [19, 75,  3, 

In [64]:
_np.isin(selector, bigarr)

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [62]:
%%timeit
_np.argwhere(bigarr == selector)

30.8 µs ± 1.39 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [59]:
%%timeit
equals = bigarr == selection

269 ms ± 3.85 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
from timeit import 